#!/usr/bin/env bash
# Configuration lines to enable connection to server without
# typing a password

Host *
    PasswordAuthentication no

Host myserver
    Hostname <100.26.237.26>
    User <ubuntu>
    IdentityFile ~/.ssh/school
